# Generated by Django 2.2.5 on 2019-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.IntegerField(max_length=10)),
                ('hastags', models.TextField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballLeaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballLeaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SoccerLeaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('screen_name', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20, null=True)),
                ('lname', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
