# Generated by Django 2.2.5 on 2019-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_auto_20191030_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='twitter_id',
            field=models.IntegerField(),
        ),
    ]
