# Generated by Django 2.2.5 on 2020-01-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_auto_20200113_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
