# Generated by Django 2.2.5 on 2020-02-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0007_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballleaderboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
