# Generated by Django 2.2.5 on 2020-02-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0008_auto_20200201_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
