# Generated by Django 2.2.5 on 2020-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0009_auto_20200202_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='hastags',
            new_name='hashtags',
        ),
    ]
