# Generated by Django 2.2.5 on 2020-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0010_auto_20200203_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballleaderboard',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='footballleaderboard',
            name='user_id',
        ),
        migrations.AddField(
            model_name='basketballleaderboard',
            name='uid',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='footballleaderboard',
            name='uid',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='hashtags',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='interval',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='server_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hashtags',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basketballleaderboard',
            name='score',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='footballleaderboard',
            name='score',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='soccerleaderboard',
            name='score',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='soccerleaderboard',
            name='user_id',
            field=models.TextField(max_length=60),
        ),
    ]
