# Generated by Django 2.2.5 on 2020-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0011_auto_20200203_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballleaderboard',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='footballleaderboard',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='soccerleaderboard',
            name='score',
            field=models.IntegerField(),
        ),
    ]
