# Generated by Django 3.0.3 on 2020-02-19 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0012_auto_20200203_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exception', models.TextField(max_length=100, null=True)),
                ('message', models.TextField(max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
